### Ticket
[TVGUI-5](https://natalie-g-projects.atlassian.net/browse/TVGUI-5)

### Description
This PR updates the presentation and layout for the Show List page.

Ant Design's Card component has been used to present the information about each show being searched, and provides the custom typing for the search item.